apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuzora-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuzora-auth
  template:
    metadata:
      labels:
        app: kuzora-auth
    spec:
      containers:
        - name: kuzora-auth
          image: gkuzora/auth-service:latest
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: healthz/ready
              port: 8080
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 2
          livenessProbe:
            httpGet:
              path: healthz/up
              port: 8080
            failureThreshold: 10
            initialDelaySeconds: 3
            periodSeconds: 2
          ports:
            - containerPort: 8080
          volumeMounts:
          - mountPath: "/var/www/face_verification/kuzora/vectors"
            name: vector-volume
          env:
            - name: CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  name: kuzora-auth-configmap
                  key: config_path
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: kuzora-auth-configmap
                  key: pythonpath
            - name: ALEMBIC_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: kuzora-auth-configmap
                  key: alembic_config
            - name: SECRETS_PATH
              valueFrom:
                configMapKeyRef:
                  name: kuzora-auth-configmap
                  key: secrets_path
      volumes:
        - name: vector-volume
          persistentVolumeClaim:
            claimName: kuzora-vectors-pvc
