apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuzora-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuzora-auth
  template:
    metadata:
      labels:
        app: kuzora-auth
    spec:
      containers:
        - name: kuzora-auth
          image: ...
          resources:
            limits:
              memory: "200Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  name: kuzora-auth-configmap
                  key: config_path
            - name: PYTHONPATH
              valueFrom:
                configMapKeyRef:
                  name: kuzora-auth-configmap
                  key: pythonpath
