version: "3"

services:
  app:
    container_name: "auth-service-kuzora"
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "28080:8080"
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PYTHONPATH=/workspace/src
      - SECRETS_PATH=/run/secrets/jwt_secrets
    secrets:
      - jwt_secrets
secrets:
  jwt_secrets:
    file: ./app/secrets
